default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bagni_development

test:
  <<: *default
  database: bagni_test

production:
  <<: *default
  database: bagni_production
  username: bagni
  password: bagni