development: &default
  mode: sandbox
  client_id: ARj50gjdzXtxfeUoR6XEEaOFET8tEEYSxB62R3pomIH5JhSddK8Iz6QHKA-q3CvkzfLHqZ20btC3oMN8
  client_secret: EJP4hPizDCBEF4LysSZjQ54vJyDH1Lzhsm7jfOxduWaCusfZGcyw5B193nDS0mE6XCiFVF68P2DN7ubd
  app_id: APP-80W284485P519543T
  username: info_api1.cubey.co
  password: V7PM5PTEDJ7TZVF9
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31ACq0covWSfI1YdpsZXkHkKtqRyut
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: info-facilitator@cubey.co
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET