development: &default
  mode: sandbox
  client_id: AT7apDg2RDt_r5g6KeMsgYxLcjXoiTN6SAU1YPx6TgWxmhkVfz3opiRjXjlR5ZGpsKUJIqS3DFqYBwlL
  client_secret: EOZTW2xfhARcVNaCL4zaf-LHHTYf1ybRNmFspjyWA7T27trOswfhTtiHboKJPmlqfCq2nOPIQNLEopBf
  app_id: APP-80W284485P519543T
  username: jigachok_api1.gmail.com
  password: 8W4FJVMXGE83926K
  signature: AalxF-vd0O7KSFTlrdeo2XqkZsJHADS4CyU-BEAYOmxK0uRbbKRKfysI
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: jigachok_api1.gmail.com
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET